<?php 
global $language_content; 
if($language_content->language == "es"){
?>
<div class="row"><div id="font-block-2" class="large-12 columns"><div class="row"><div class="large-5 small-12 columns"><div class="large-12 columns video"><div class="view view-views-front view-id-views_front view-display-id-block_9 view-dom-id-c05076a3bea287ea43998408048de98f"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first views-row-last"><div class="slide-container"><div class="slide-image">
<a href="#" data-reveal-id="videoModal"><div class="field-content">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/flexslider_full/public/MED-VID-Recaptura.jpg?itok=teRTkown" width="800" height="500" alt=""></div><div class="slide-caption">
<span class="icons">
<span class="fa fa-youtube"></span></span><p class="slider-name">
<span class="field-content">Descubre Honduras</span></p></div></a></div></div></div></div></div></div><div class="large-12 columns"><div class="view view-views-front view-id-views_front view-display-id-block_6 view-dom-id-efbe16c49ed3e62eedb329d6a59f7e3a jquery-once-1-processed"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first"><div class="image-container front-image large-12 columns"><div class="fade"><div class="views-content-title">
<span class="field-content">
<a href="/es/redes-sociales/una-gu%C3%ADa-de-viajes-hecha-en-honduras">Una guía de viajes hecha en Honduras</a></span></div><div class="image"><div class="detalle"><div class="row"><div class="large-12 columns"><div class="large-7 columns"><div class="field-content"><p>La guía de turismo más reconocida de Honduras: Honduras Tips, un medio digital del Grupo OPSA.</p></div></div><div class=""><div class="field-content">
<a href="/es/redes-sociales/una-gu%C3%ADa-de-viajes-hecha-en-honduras">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/gimages__207_x_240_/public/MED-SMD-HondurasTips-20140803_600.jpg?itok=KTCjC8CN" width="205" height="122" alt=""></a></div></div></div></div><div class="row"><div class="large-6 columns"><div class="field-content">
<a href="http://www.twitter.com/hondurastips" target="_blank" rel="nofollow">@HondurasTips</a></div></div><div class="large-6 columns"><div class="field-content"><div class="zf-1col taxonomy-term vocabulary-redes-sociales view-mode-full row"><div class="group-content large-12"><div class="field field-name-field-imagen-logo field-type-image field-label-hidden field-wrapper">
<a href="/es/redes-sociales/twetter">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/ico__35x35_/public/Twitter-Logo1.png?itok=_5NdgUqf" width="35" height="35" alt=""></a></div></div></div></div></div></div></div></div></div></div></div><div class="views-row views-row-2 views-row-even views-row-last"><div class="image-container front-image large-12 columns"><div class="fade"><div class="views-content-title">
<span class="field-content">
<a href="/es/redes-sociales/escucha-cala-sobre-honduras">Escucha a Cala sobre Honduras</a></span></div><div class="image"><div class="detalle"><div class="row"><div class="large-12 columns"><div class="large-7 columns"><div class="field-content"><p><u>
<a href="http://www.twitter.com/CalaCNN">@CALACNN</a></u>: De mi propia voz, #LaColumnaDeCALA de esta semana trib</p></div></div><div class=""><div class="field-content">
<a href="/es/redes-sociales/escucha-cala-sobre-honduras">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/gimages__207_x_240_/public/MED-SMD-Cala-soundcloud-20140803_600_0.jpg?itok=LdddYQ8M" width="205" height="122" alt=""></a></div></div></div></div><div class="row"><div class="large-6 columns"><div class="field-content">
<a href="https://t.co/91pidF71Rv" target="_blank" rel="nofollow">@CalaCNN</a></div></div><div class="large-6 columns"><div class="field-content"><div class="zf-1col taxonomy-term vocabulary-redes-sociales view-mode-full row"><div class="group-content large-12"><div class="field field-name-field-imagen-logo field-type-image field-label-hidden field-wrapper">
<a href="/es/redes-sociales/twetter">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/ico__35x35_/public/Twitter-Logo1.png?itok=_5NdgUqf" width="35" height="35" alt=""></a></div></div></div></div></div></div></div></div></div></div></div><div class="large-12 columns rest"><span>
<a href="http://demo2.webmasterhn.com/es/gallerys">Mas..</a></span></div></div></div></div><div class="large-12 columns"><div class="hash"><div class="row"><div class="large-12 columns">
<section class="block block-block block-block-10"><p>
<a href="https://twitter.com/search?src=typd&amp;q=%23Enjoyhonduras" target="_blank">#Enjoyhonduras</a>&nbsp; &nbsp; &nbsp;&nbsp;
<a href="https://twitter.com/search?q=%23Hondurastravel&amp;src=typd" target="_blank">#Hondurastravel</a></p> </section></div></div></div></div></div><div class="large-7 small-12 columns"><div class="large-12 columns"><div class="view view-views-front view-id-views_front view-display-id-block_2 view-dom-id-f6a7156ef264b7ef365ae7335ba1cf52"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first views-row-last"><div class="views-field views-field-title">
<span class="field-content">
<a href="/es/blog/el-eco-de-gracias-convoca">El eco de Gracias Convoca</a></span></div><div class="views-field views-field-field-fuente"><div class="field-content">Cámara de Turismo de Gracias</div></div><div class="views-field views-field-body">
<em class="field-content"><p>El eco de Gracias Convoca resuena por segundo año desde Celaque, para compartir cultura, arte e identidad común.</p> </em></div></div></div></div></div><div class="large-12 columns blog-slide"><div class="view view-views-front view-id-views_front view-display-id-block_3 view-dom-id-c6555f1ab77fa845b2e975d23c355db2"><div class="view-content"><div class="skin-default"><div id="views_slideshow_cycle_main_views_front-block_3" class="views_slideshow_cycle_main views_slideshow_main viewsSlideshowCycle-processed"><div id="views_slideshow_cycle_teaser_section_views_front-block_3" class="views-slideshow-cycle-main-frame views_slideshow_cycle_teaser_section" style="position: relative; width: 261px; height: 369px;"><div id="views_slideshow_cycle_div_views_front-block_3_0" class="views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-1 views-row-odd" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 3; opacity: 0; width: 261px; height: 369px;"><div class="views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-odd views-row-first"><div class="views-field views-field-field-imagen-principal"><div class="field-content">
<a href="/es/blog/el-eco-de-gracias-convoca">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/slider_blog__290_x_370_/public/MED-BLG-El-eco-de-Gracias-Convoca-20140803_290_0.jpg?itok=fqJBAlJE" width="270" height="370" alt=""></a></div></div><div class="views-field views-field-view-node">
<span class="field-content blog-slider-link">
<a href="/es/blog/el-eco-de-gracias-convoca">Leer mas...</a></span></div></div></div><div id="views_slideshow_cycle_div_views_front-block_3_1" class="views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-2 views_slideshow_cycle_hidden views-row-even" style="position: absolute; top: 0px; left: 0px; display: block; z-index: 4; opacity: 1; width: 261px; height: 369px;"><div class="views-slideshow-cycle-main-frame-row-item views-row views-row-1 views-row-even"><div class="views-field views-field-field-imagen-principal"><div class="field-content">
<a href="/es/blog/despega-hondurastravel">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/slider_blog__290_x_370_/public/MED-BLG-Lanzamiento-HNT-20140803_290_0.jpg?itok=X84lvJes" width="270" height="370" alt=""></a></div></div><div class="views-field views-field-view-node">
<span class="field-content blog-slider-link">
<a href="/es/blog/despega-hondurastravel">Leer mas...</a></span></div></div></div><div id="views_slideshow_cycle_div_views_front-block_3_2" class="views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-3 views_slideshow_cycle_hidden views-row-odd" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 3; opacity: 0; width: 261px; height: 369px;"><div class="views-slideshow-cycle-main-frame-row-item views-row views-row-2 views-row-odd views-row-last"><div class="views-field views-field-field-imagen-principal"><div class="field-content">
<a href="/es/blog/relax-entre-tiburones">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/slider_blog__290_x_370_/public/MED-GLG-Relax-entre-tiburones-20140803_290nueva.jpg?itok=JGkHmbnE" width="270" height="370" alt=""></a></div></div><div class="views-field views-field-view-node">
<span class="field-content blog-slider-link">
<a href="/es/blog/relax-entre-tiburones">Leer mas...</a></span></div></div></div></div></div><div class="views-slideshow-controls-bottom clearfix"><div id="widget_pager_bottom_views_front-block_3" class="views-slideshow-pager-fields widget_pager widget_pager_bottom views_slideshow_pager_field views-slideshow-pager-field-processed"><div id="views_slideshow_pager_field_item_bottom_views_front-block_3_0" class="views-slideshow-pager-field-item views_slideshow_pager_field_item views-row-odd views-row-first"><div class="views-field-title"><div class="views-content-title"> El eco de Gracias Convoca</div></div><div class="views-field-field-fuente"><div class="views-content-field-fuente"> Cámara de Turismo de Gracias</div></div><div class="views-field-body"><div class="views-content-body"><p>El eco de Gracias Convoca resuena por segundo año desde Celaque, para compartir cultura, arte e identidad común.</p></div></div><div class="views-field-view-node"><div class="views-content-view-node">
<a href="/es/blog/el-eco-de-gracias-convoca">Leer mas...</a></div></div></div><div id="views_slideshow_pager_field_item_bottom_views_front-block_3_1" class="views-slideshow-pager-field-item views_slideshow_pager_field_item views-row-even active"><div class="views-field-title"><div class="views-content-title"> Despega Honduras.Travel</div></div><div class="views-field-field-fuente"><div class="views-content-field-fuente"> Honduras.Travel</div></div><div class="views-field-body"><div class="views-content-body"><p>Honduras presenta <em>urbi et orbi</em> su portal oficial turístico el lunes 4 de agosto de 2014.</p></div></div><div class="views-field-view-node"><div class="views-content-view-node">
<a href="/es/blog/despega-hondurastravel">Leer mas...</a></div></div></div><div id="views_slideshow_pager_field_item_bottom_views_front-block_3_2" class="views-slideshow-pager-field-item views_slideshow_pager_field_item views-row-odd views-row-last"><div class="views-field-title"><div class="views-content-title"> Relax entre tiburones</div></div><div class="views-field-field-fuente"><div class="views-content-field-fuente"></div></div><div class="views-field-body"><div class="views-content-body"><p>¿Y si al imaginarte nadando entre tiburones en lugar de la canción de "Jaws" escuchas "I feel good"?</p></div></div><div class="views-field-view-node"><div class="views-content-view-node">
<a href="/es/blog/relax-entre-tiburones">Leer mas...</a></div></div></div></div></div></div></div></div></div><div class="large-12 columns"><h5>Calendario de Eventos</h5><div class="view view-eventos-y-festividades view-id-eventos_y_festividades view-display-id-block view-dom-id-6f9b2fb457844033b9de59dc196c0f7b"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first"><div class="views-field views-field-body"><div class="field-content"><div class="row"><div class="large-12 columns"><div class="dates large-2 columns"><div class="day">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-08-04T00:00:00-06:00">04</span></div><div class="mouth">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-08-04T00:00:00-06:00">Agosto</span></div><div class="year">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-08-04T00:00:00-06:00">2014</span></div></div><div class="txbody large-10 columns"><h4>
<a href="/es/eventos-y-calendario/despega-hondurastravel">Despega Honduras.Travel</a></h4><p>El lunes 4 de agosto despega en Casa Presidencial el portal nacional de turismo de Honduras: Hondras.Travel.</p></div></div></div></div></div></div><div class="views-row views-row-2 views-row-even views-row-last"><div class="views-field views-field-body"><div class="field-content"><div class="row"><div class="large-12 columns"><div class="dates large-2 columns"><div class="day">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-07-30T00:00:00-06:00">30</span></div><div class="mouth">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-07-30T00:00:00-06:00">Julio</span></div><div class="year">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-07-30T00:00:00-06:00">2014</span></div></div><div class="txbody large-10 columns"><h4>
<a href="/es/eventos-y-calendario/explora-el-caribe-casi-1000-metros">Explora el Caribe a casi 1000 metros</a></h4><p>El Museo para la Identidad Nacional te invita a
<a href="http://www.min.hn/arrecifes-de-coral/">explorar la parte más viva del Arrecife Mesoameric</a></p></div></div></div></div></div></div></div></div></div></div></div></div></div>	

<?php	
} else {
?>



<div class="row"><div id="font-block-2" class="large-12 columns"><div class="row"><div class="large-5 small-12 columns"><div class="large-12 columns video"><div class="view view-views-front view-id-views_front view-display-id-block_9 view-dom-id-07271bad010bca8c355f729221ad8bf9"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first views-row-last"><div class="slide-container"><div class="slide-image">
<a href="#" data-reveal-id="videoModal"><div class="field-content">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/flexslider_full/public/MED-VID-Recaptura_0.jpg?itok=JdGrt7by" width="800" height="500" alt=""></div><div class="slide-caption">
<span class="icons">
<span class="fa fa-youtube"></span></span><p class="slider-name">
<span class="field-content">Discover Honduras</span></p></div></a></div></div></div></div></div></div><div class="large-12 columns"><div class="view view-views-front view-id-views_front view-display-id-block_6 view-dom-id-46a4bd18d8eabd007d8101d332c72ee2 jquery-once-1-processed"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first"><div class="image-container front-image large-12 columns"><div class="fade"><div class="views-content-title">
<span class="field-content">
<a href="/en/social-networks/santos-arz%C3%BA-quioto-tedx-tegucigalpa">Santos Arzú Quioto in TEDx Tegucigalpa. </a></span></div><div class="image"><div class="detalle"><div class="row"><div class="large-12 columns"><div class="large-7 columns"><div class="field-content"><p><strong>Between "The Carpet" and&nbsp;"The Draemcatcher".</strong></p></div></div><div class=""><div class="field-content">
<a href="/en/social-networks/santos-arz%C3%BA-quioto-tedx-tegucigalpa">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/gimages__207_x_240_/public/MED-SMD-SantosArzu-enTEDx-20140803_600.jpg?itok=w-xSqVzo" width="205" height="137" alt=""></a></div></div></div></div><div class="row"><div class="large-6 columns"><div class="field-content">
<a href="https://www.facebook.com/TEDxTegucigalpa/photos/pb.241928552524563.-2207520000.1407093620./681586645225416/?type=1&amp;theater" target="_blank" rel="nofollow">TEDx Tegucigalpa</a></div></div><div class="large-6 columns"><div class="field-content"></div></div></div></div></div></div></div></div><div class="views-row views-row-2 views-row-even views-row-last"><div class="image-container front-image large-12 columns"><div class="fade"><div class="views-content-title">
<span class="field-content">
<a href="/en/social-networks/honduras-great-common-point">Honduras is Great, a common point. </a></span></div><div class="image"><div class="detalle"><div class="row"><div class="large-12 columns"><div class="large-7 columns"><div class="field-content"><p>The most active facebook page for information on Honduras.</p></div></div><div class=""><div class="field-content">
<a href="/en/social-networks/honduras-great-common-point">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/gimages__207_x_240_/public/MED-SMD-Honduras-Is-Great-20140803_600_Nueva3.jpg?itok=gIPeWxna" width="205" height="121" alt=""></a></div></div></div></div><div class="row"><div class="large-6 columns"><div class="field-content">
<a href="https://www.facebook.com/pages/Honduras-is-Great/127171764091465?fref=ts" target="_blank" rel="nofollow">Honduras is Great</a></div></div><div class="large-6 columns"><div class="field-content"><div class="zf-1col taxonomy-term vocabulary-redes-sociales view-mode-full row"><div class="group-content large-12"><div class="field field-name-field-imagen-logo field-type-image field-label-hidden field-wrapper">
<a href="/en/taxonomy/term/92">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/ico__35x35_/public/new-facebook-logo-300x300.png?itok=GSgO-xTY" width="35" height="35" alt=""></a></div></div></div></div></div></div></div></div></div></div></div><div class="large-12 columns rest"><span>
<a href="http://demo2.webmasterhn.com/es/gallerys">Mas..</a></span></div></div></div></div><div class="large-12 columns"><div class="hash"><div class="row"><div class="large-12 columns">
<a href="https://twitter.com/search?src=typd&amp;q=%23Enjoyhonduras" target="_blank">#Enjoyhonduras</a>&nbsp; &nbsp; &nbsp;&nbsp;
<a href="https://twitter.com/search?q=%23Hondurastravel&amp;src=typd" target="_blank">#Hondurastravel</a></p> </section></div></div></div></div></div><div class="large-7 small-12 columns"><div class="large-12 columns"><div class="view view-views-front view-id-views_front view-display-id-block_2 view-dom-id-be34ebf4f2153e0dfedce2ab53e02eb2"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first views-row-last"><div class="views-field views-field-title">
<span class="field-content">
<a href="/en/events-and-calendar/hamlet-cop%C3%A1n-ruinas">Hamlet at Copán Ruinas</a></span></div><div class="views-field views-field-field-fuente"><div class="field-content"></div></div><div class="views-field views-field-body">
<em class="field-content"><p>On Saturday August 16 the&nbsp;<u>
<a href="http://www.shakespearesglobe.com/your-visit/frequently-asked-questions">Shakes</a></u></p></em></div></div></div></div></div><div class="large-12 columns blog-slide"><div class="view view-views-front view-id-views_front view-display-id-block_3 view-dom-id-2cb956ec5a1f60d40e31098319e910a0"><div class="view-content"><div class="skin-default"><div id="views_slideshow_cycle_main_views_front-block_3" class="views_slideshow_cycle_main views_slideshow_main viewsSlideshowCycle-processed"><div id="views_slideshow_cycle_teaser_section_views_front-block_3" class="views-slideshow-cycle-main-frame views_slideshow_cycle_teaser_section" style="position: relative; width: 261px; height: 370px;"><div id="views_slideshow_cycle_div_views_front-block_3_0" class="views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-1 views-row-odd" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 3; opacity: 0;"><div class="views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-odd views-row-first"><div class="views-field views-field-field-imagen-principal"><div class="field-content">
<a href="/en/blog/hamlet-among-maya">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/slider_blog__290_x_370_/public/MED-GLG-Hamlet-entre-los-mayas-20140803_290.jpg?itok=wg808IRP" width="270" height="370" alt=""></a></div></div><div class="views-field views-field-view-node">
<span class="field-content blog-slider-link">
<a href="/en/blog/hamlet-among-maya">Leer mas...</a></span></div></div></div><div id="views_slideshow_cycle_div_views_front-block_3_1" class="views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-2 views_slideshow_cycle_hidden views-row-even" style="position: absolute; top: 0px; left: 0px; display: none; z-index: 3; opacity: 0; width: 261px; height: 370px;"><div class="views-slideshow-cycle-main-frame-row-item views-row views-row-1 views-row-even"><div class="views-field views-field-field-imagen-principal"><div class="field-content">
<a href="/en/blog/echo-gracias-convoca">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/slider_blog__290_x_370_/public/MED-BLG-El-eco-de-Gracias-Convoca-20140803_290_0.jpg?itok=fqJBAlJE" width="270" height="370" alt=""></a></div></div><div class="views-field views-field-view-node">
<span class="field-content blog-slider-link">
<a href="/en/blog/echo-gracias-convoca">Leer mas...</a></span></div></div></div><div id="views_slideshow_cycle_div_views_front-block_3_2" class="views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-3 views_slideshow_cycle_hidden views-row-odd" style="position: absolute; top: 0px; left: 0px; display: block; z-index: 4; opacity: 1; width: 261px; height: 370px;"><div class="views-slideshow-cycle-main-frame-row-item views-row views-row-2 views-row-odd views-row-last"><div class="views-field views-field-field-imagen-principal"><div class="field-content">
<a href="/en/blog/relax-among-sharks">
<img typeof="foaf:Image" src="http://honduras.travel/sites/default/files/styles/slider_blog__290_x_370_/public/MED-GLG-Relax-entre-tiburones-20140803_290nueva.jpg?itok=JGkHmbnE" width="270" height="370" alt=""></a></div></div><div class="views-field views-field-view-node">
<span class="field-content blog-slider-link">
<a href="/en/blog/relax-among-sharks">Leer mas...</a></span></div></div></div></div></div><div class="views-slideshow-controls-bottom clearfix"><div id="widget_pager_bottom_views_front-block_3" class="views-slideshow-pager-fields widget_pager widget_pager_bottom views_slideshow_pager_field views-slideshow-pager-field-processed"><div id="views_slideshow_pager_field_item_bottom_views_front-block_3_0" class="views-slideshow-pager-field-item views_slideshow_pager_field_item views-row-odd views-row-first"><div class="views-field-title"><div class="views-content-title"> Hamlet among the Maya</div></div><div class="views-field-field-fuente"><div class="views-content-field-fuente"></div></div><div class="views-field-body"><div class="views-content-body"><p>Sometimes, creatures, places and ocassions only get together after centuries. Hamlet in Copan Ruinas in August 2014 is one of those times.</p></div></div><div class="views-field-view-node"><div class="views-content-view-node">
<a href="/en/blog/hamlet-among-maya">Leer mas...</a></div></div></div><div id="views_slideshow_pager_field_item_bottom_views_front-block_3_1" class="views-slideshow-pager-field-item views_slideshow_pager_field_item views-row-even"><div class="views-field-title"><div class="views-content-title"> The echo of Gracias Convoca</div></div><div class="views-field-field-fuente"><div class="views-content-field-fuente"> Cámara de Turismo de Gracias</div></div><div class="views-field-body"><div class="views-content-body"><p>The echo of Gracias Convoca resonates for second year from Celaque, sharing culture, art and common identity.</p></div></div><div class="views-field-view-node"><div class="views-content-view-node">
<a href="/en/blog/echo-gracias-convoca">Leer mas...</a></div></div></div><div id="views_slideshow_pager_field_item_bottom_views_front-block_3_2" class="views-slideshow-pager-field-item views_slideshow_pager_field_item views-row-odd views-row-last active"><div class="views-field-title"><div class="views-content-title"> Relax among sharks</div></div><div class="views-field-field-fuente"><div class="views-content-field-fuente"></div></div><div class="views-field-body"><div class="views-content-body"><p>How if when you imagine yourself swimming among sharks instead of the song from "Jaws" you listen "I feel good"?</p></div></div><div class="views-field-view-node"><div class="views-content-view-node">
<a href="/en/blog/relax-among-sharks">Leer mas...</a></div></div></div></div></div></div></div></div></div><div class="large-12 columns"><h5>Event's Calendar</h5><div class="view view-eventos-y-festividades view-id-eventos_y_festividades view-display-id-block view-dom-id-553af1b22cb209a4b60e44b3a59281dd"><div class="view-content"><div class="views-row views-row-1 views-row-odd views-row-first"><div class="views-field views-field-body"><div class="field-content"><div class="row"><div class="large-12 columns"><div class="dates large-2 columns"><div class="day">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-08-04T00:00:00-06:00">04</span></div><div class="mouth">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-08-04T00:00:00-06:00">August</span></div><div class="year">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-08-04T00:00:00-06:00">2014</span></div></div><div class="txbody large-10 columns"><h4>
<a href="/en/events-and-calendar/hondurastravel-takes">Honduras.Travel takes off</a></h4><p>On Monday, August 4 at the Presidential Palace takes off the national tourism portal of Honduras:
<a href="http://honduras.travel"><u><em>Honduras</em></u></a></p></div></div></div></div></div></div><div class="views-row views-row-2 views-row-even views-row-last"><div class="views-field views-field-body"><div class="field-content"><div class="row"><div class="large-12 columns"><div class="dates large-2 columns"><div class="day">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-07-30T00:00:00-06:00">30</span></div><div class="mouth">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-07-30T00:00:00-06:00">July</span></div><div class="year">
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2014-07-30T00:00:00-06:00">2014</span></div></div><div class="txbody large-10 columns"><h4>
<a href="/en/events-and-calendar/explore-caribbean-nearly-1000-meters">Explore the Caribbean nearly at 1000 meters.</a></h4><p>The National Identity Museum (MIN) invites you <em>
<a href="http://www.min.hn/arrecifes-de-coral/">to explore the most lively part of the Mesoamer</a></em></p></div></div></div></div></div></div></div></div></div></div></div></div></div>


<?php
}

